# CSV Function

In [22]:
import pandas as pd
import numpy as np

In [23]:
csv_1 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv")
csv_1

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
1,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
2,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
3,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
4,1005,Vikram Gupta,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
5,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
6,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
7,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
8,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
9,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
10,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
11,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
12,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
13,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
14,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

In [24]:
csv_1.index # for index

RangeIndex(start=0, stop=15, step=1)

In [25]:
csv_1.columns # for column names

Index(['Transaction_ID', 'Customer_Name', 'City', 'Category', 'Product',
       'Price', 'Quantity', 'Payment_Method', 'Order_Date', 'Rating',
       'Total_Amount'],
      dtype='str')

In [26]:
csv_1.describe()

       Transaction_ID         Price   Quantity     Rating  Total_Amount
count       15.000000     15.000000  15.000000  15.000000     15.000000
mean      1008.000000   9986.666667   1.600000   4.260000  11286.666667
std          4.472136  14216.834421   0.910259   0.313506  13581.598195
min       1001.000000   1200.000000   1.000000   3.800000   2200.000000
25%       1004.500000   2650.000000   1.000000   4.000000   4750.000000
50%       1008.000000   4100.000000   1.000000   4.200000   6000.000000
75%       1011.500000  10250.000000   2.000000   4.500000  10800.000000
max       1015.000000  55000.000000   4.000000   4.800000  55000.000000

In [27]:
csv_1.head() # it shows on fierst five data of csv file , 
csv_1.head(3) # it shows on first three data of csv file ,

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
1,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
2,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0

In [28]:
csv_1.tail() # last 5 rows

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
10,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
11,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
12,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
13,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
14,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

In [29]:
csv_1[5:11] # specific rows

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
5,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
6,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
7,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
8,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
9,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
10,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0

In [30]:
csv_1.to_numpy() # conver into numpy array

array([[1001, 'Aarav Sharma', 'Delhi', 'Electronics', 'Laptop', 55000.0,
        1, 'UPI', '2024-01-15', 4.5, 55000.0],
       [1002, 'Ananya Patel', 'Mumbai', 'Clothing', 'T-Shirt', 1200.0, 3,
        'Credit Card', '2024-01-18', 4.0, 3600.0],
       [1003, 'Rohan Verma', 'Bengaluru', 'Electronics', 'Smartphone',
        25000.0, 1, 'UPI', '2024-01-20', 4.8, 25000.0],
       [1004, 'Priya Singh', 'Delhi', 'Home & Kitchen', 'Blender',
        3500.0, 2, 'Debit Card', '2024-01-22', 3.9, 7000.0],
       [1005, 'Vikram Gupta', 'Hyderabad', 'Electronics', 'Headphones',
        2500.0, 2, 'Net Banking', '2024-01-25', 4.2, 5000.0],
       [1006, 'Neha Reddy', 'Bengaluru', 'Clothing', 'Jeans', 2200.0, 1,
        'UPI', '2024-01-28', 4.1, 2200.0],
       [1007, 'Karan Malhotra', 'Mumbai', 'Home & Kitchen', 'Microwave',
        6500.0, 1, 'Credit Card', '2024-02-02', 4.6, 6500.0],
       [1008, 'Sanya Iyer', 'Chennai', 'Electronics', 'Smartwatch',
        4500.0, 1, 'UPI', '2024-02-05', 4.3, 4500.0],
       [1009, 'Rahul Das', 'Kolkata', 'Clothing', 'Jacket', 3800.0, 2,
        'Debit Card', '2024-02-10', 3.8, 7600.0],
       [1010, 'Meera Joshi', 'Pune', 'Home & Kitchen', 'Air Fryer',
        5200.0, 1, 'Credit Card', '2024-02-12', 4.7, 5200.0],
       [1011, 'Amit Kumar', 'Delhi', 'Electronics', 'Tablet', 18000.0, 1,
        'UPI', '2024-02-15', 4.4, 18000.0],
       [1012, 'Pooja Hegde', 'Mumbai', 'Clothing', 'Dress', 2800.0, 2,
        'Credit Card', '2024-02-18', 4.0, 5600.0],
       [1013, 'Siddharth Roy', 'Bengaluru', 'Electronics', 'Monitor',
        14000.0, 1, 'Net Banking', '2024-02-20', 4.5, 14000.0],
       [1014, 'Riya Sen', 'Hyderabad', 'Home & Kitchen', 'Coffee Maker',
        4100.0, 1, 'UPI', '2024-02-22', 4.2, 4100.0],
       [1015, 'Deepak Verma', 'Pune', 'Clothing', 'Shirt', 1500.0, 4,
        'Debit Card', '2024-02-25', 3.9, 6000.0]], dtype=object)

In [31]:
v = np.asarray(csv_1) # 2 method to convert csv to numpy array
print(v)

[[1001 'Aarav Sharma' 'Delhi' 'Electronics' 'Laptop' 55000.0 1 'UPI'
  '2024-01-15' 4.5 55000.0]
 [1002 'Ananya Patel' 'Mumbai' 'Clothing' 'T-Shirt' 1200.0 3
  'Credit Card' '2024-01-18' 4.0 3600.0]
 [1003 'Rohan Verma' 'Bengaluru' 'Electronics' 'Smartphone' 25000.0 1
  'UPI' '2024-01-20' 4.8 25000.0]
 [1004 'Priya Singh' 'Delhi' 'Home & Kitchen' 'Blender' 3500.0 2
  'Debit Card' '2024-01-22' 3.9 7000.0]
 [1005 'Vikram Gupta' 'Hyderabad' 'Electronics' 'Headphones' 2500.0 2
  'Net Banking' '2024-01-25' 4.2 5000.0]
 [1006 'Neha Reddy' 'Bengaluru' 'Clothing' 'Jeans' 2200.0 1 'UPI'
  '2024-01-28' 4.1 2200.0]
 [1007 'Karan Malhotra' 'Mumbai' 'Home & Kitchen' 'Microwave' 6500.0 1
  'Credit Card' '2024-02-02' 4.6 6500.0]
 [1008 'Sanya Iyer' 'Chennai' 'Electronics' 'Smartwatch' 4500.0 1 'UPI'
  '2024-02-05' 4.3 4500.0]
 [1009 'Rahul Das' 'Kolkata' 'Clothing' 'Jacket' 3800.0 2 'Debit Card'
  '2024-02-10' 3.8 7600.0]
 [1010 'Meera Joshi' 'Pune' 'Home & Kitchen' 'Air Fryer' 5200.0 1
  'Credit Card' '2024-02-12' 4.7 5200.0]
 [1011 'Amit Kumar' 'Delhi' 'Electronics' 'Tablet' 18000.0 1 'UPI'
  '2024-02-15' 4.4 18000.0]
 [1012 'Pooja Hegde' 'Mumbai' 'Clothing' 'Dress' 2800.0 2 'Credit Card'
  '2024-02-18' 4.0 5600.0]
 [1013 'Siddharth Roy' 'Bengaluru' 'Electronics' 'Monitor' 14000.0 1
  'Net Banking' '2024-02-20' 4.5 14000.0]
 [1014 'Riya Sen' 'Hyderabad' 'Home & Kitchen' 'Coffee Maker' 4100.0 1
  'UPI' '2024-02-22' 4.2 4100.0]
 [1015 'Deepak Verma' 'Pune' 'Clothing' 'Shirt' 1500.0 4 'Debit Card'
  '2024-02-25' 3.9 6000.0]]

In [32]:
csv_1.sort_index(axis=0, ascending=False) # sort by index in descending order

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
14,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0
13,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
12,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
11,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
10,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
9,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
8,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
7,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
6,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
5,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
4,1005,Vikram Gupta,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
3,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
2,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
1,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
0,1001,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0

In [33]:
csv_1.loc[0,"Customer_Name"] = "kallu" # it usedd to change the value of the cell
csv_1

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001,kallu,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
1,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
2,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
3,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
4,1005,Vikram Gupta,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
5,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
6,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
7,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
8,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
9,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
10,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
11,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
12,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
13,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
14,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

# loc function

In [ ]:
csv_1.loc[[3,7],["Customer_Name","Product"]] # we can get specific data

    Customer_Name     Product
3     Priya Singh     Blender
4    Vikram Gupta  Headphones
5      Neha Reddy       Jeans
6  Karan Malhotra   Microwave
7      Sanya Iyer  Smartwatch

In [39]:
csv_1.loc[3:7,["Customer_Name","Product"]] 
csv_1.loc[[3,7],:]

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
3,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
7,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0

In [40]:
csv_1.loc[3:7,["Customer_Name","Product"]]

    Customer_Name     Product
3     Priya Singh     Blender
4    Vikram Gupta  Headphones
5      Neha Reddy       Jeans
6  Karan Malhotra   Microwave
7      Sanya Iyer  Smartwatch

In [43]:
csv_1.iloc[0,4] #it gives particular row

'Laptop'

In [47]:
csv_1.drop("Customer_Name",axis=1) #drop column

,Transaction_ID,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
1,1002,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
2,1003,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
3,1004,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
4,1005,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
5,1006,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
6,1007,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
7,1008,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
8,1009,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
9,1010,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
10,1011,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
11,1012,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
12,1013,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
13,1014,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
14,1015,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0