# Groupby

In [21]:
import pandas as pd
import numpy as np

In [22]:
var = pd.DataFrame({'name': ['a','b','c','d','a','e','a','b','d','c'],'age':[5,4,7,3,8,2,9,1,0,6]})
var

  name  age
0    a    5
1    b    4
2    c    7
3    d    3
4    a    8
5    e    2
6    a    9
7    b    1
8    d    0
9    c    6

In [23]:
var1 = var.groupby('name')
var1

In [24]:
# for show this data 
for x ,y in var1:
    print( x , y )
    print()

a   name  age
0    a    5
4    a    8
6    a    9

b   name  age
1    b    4
7    b    1

c   name  age
2    c    7
9    c    6

d   name  age
3    d    3
8    d    0

e   name  age
5    e    2

In [25]:
# for get specific data from dataframe
var1.get_group('a')

  name  age
0    a    5
4    a    8
6    a    9

In [26]:
# for minimum and maximum ,mean
var1.min()

      age
name
a       5
b       1
c       6
d       0
e       2

In [27]:
var1.max()

      age
name
a       9
b       4
c       7
d       3
e       2

In [28]:
var1.mean()

           age
name
a     7.333333
b     2.500000
c     6.500000
d     1.500000
e     2.000000

In [29]:
# convert in list
li =list(var1)
li

[('a',
    name  age
  0    a    5
  4    a    8
  6    a    9),
 ('b',
    name  age
  1    b    4
  7    b    1),
 ('c',
    name  age
  2    c    7
  9    c    6),
 ('d',
    name  age
  3    d    3
  8    d    0),
 ('e',
    name  age
  5    e    2)]

# joining two dataframes

In [32]:
d1 =pd.DataFrame({'A':[1,3,4,8],'B':[11,22,33,44]})
d2 =pd.DataFrame({'D':[50,20],'C':[41,89]})
d1.join(d2)

   A   B     D     C
0  1  11  50.0  41.0
1  3  22  20.0  89.0
2  4  33   NaN   NaN
3  8  44   NaN   NaN

In [33]:
d2.join(d1)

    D   C  A   B
0  50  41  1  11
1  20  89  3  22

In [34]:
d2.join(d1,how='outer')

      D     C  A   B
0  50.0  41.0  1  11
1  20.0  89.0  3  22
2   NaN   NaN  4  33
3   NaN   NaN  8  44

# Append

In [36]:
d1 =pd.DataFrame({'A':[1,3,4,8],'B':[11,22,33,44]})
d2 =pd.DataFrame({'D':[50,20],'B':[41,89]})
pd.concat([d1,d2],ignore_index=True)

     A   B     D
0  1.0  11   NaN
1  3.0  22   NaN
2  4.0  33   NaN
3  8.0  44   NaN
4  NaN  41  50.0
5  NaN  89  20.0