# Dropna & Fillna

In [102]:
import pandas as pd
import numpy as np

In [103]:
csv_1 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv")
csv_1

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,NaN,NaN,Clothing,T-Shirt,NaN,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,NaN,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,NaN,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,NaN,NaN,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,NaN,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,NaN,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,NaN,1.0,Credit Card,NaN,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,NaN,2.0,Credit Card,18-02-2024,4.0,NaN
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [104]:
csv_1.dropna() # drops the rows with missing data

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [105]:
csv_1.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [106]:
csv_1.dropna(axis=0,how='any') #drops all rows with missing data

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [107]:
csv_1.dropna(subset="Total_Amount") #drops the rows with missing values

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,NaN,NaN,Clothing,T-Shirt,NaN,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,NaN,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,NaN,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,NaN,NaN,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,NaN,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,NaN,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,NaN,1.0,Credit Card,NaN,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [108]:
csv_1.dropna(inplace=True) #drops the rows with missing data
csv_1

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [109]:
csv_1.dropna(thresh=2)

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

# Fillna

In [110]:
csv_1 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv")
csv_1

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,NaN,NaN,Clothing,T-Shirt,NaN,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,NaN,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,NaN,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,NaN,NaN,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,NaN,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,NaN,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,NaN,1.0,Credit Card,NaN,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,NaN,2.0,Credit Card,18-02-2024,4.0,NaN
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [111]:
csv_1.fillna("jeevanshu")

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,jeevanshu,jeevanshu,Clothing,T-Shirt,jeevanshu,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,jeevanshu,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,jeevanshu,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,jeevanshu,jeevanshu,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,jeevanshu,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,jeevanshu,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,jeevanshu,1.0,Credit Card,jeevanshu,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,jeevanshu,2.0,Credit Card,18-02-2024,4.0,jeevanshu
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,jeevanshu,jeevanshu,jeevanshu,jeevanshu,jeevanshu,jeevanshu,jeevanshu,jeevanshu,jeevanshu,jeevanshu,jeevanshu
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [112]:
csv_1.fillna({"Customer_Name":"jeevanshu","Total_Amount":0,"Category": "not selling","Order_Date":2024})

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,jeevanshu,NaN,Clothing,T-Shirt,NaN,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,NaN,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,not selling,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,NaN,NaN,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,NaN,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,not selling,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,NaN,1.0,Credit Card,2024,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,NaN,2.0,Credit Card,18-02-2024,4.0,0.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,NaN,jeevanshu,NaN,not selling,NaN,NaN,NaN,NaN,2024,NaN,0.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [113]:
csv_1.ffill()

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,Aarav Sharma,Delhi,Clothing,T-Shirt,55000.0,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,25000.0,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,Home & Kitchen,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,2200.0,1.0,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,Credit Card,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,Electronics,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,3800.0,1.0,Credit Card,10-02-2024,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,18000.0,2.0,Credit Card,18-02-2024,4.0,18000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [114]:
csv_1.bfill()

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,Rohan Verma,Bengaluru,Clothing,T-Shirt,25000.0,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,2500.0,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,Clothing,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,4500.0,1.0,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,Debit Card,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,Home & Kitchen,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,18000.0,1.0,Credit Card,15-02-2024,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,14000.0,2.0,Credit Card,18-02-2024,4.0,14000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [115]:
csv_1.ffill(axis=1)

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,1002.0,1002.0,Clothing,T-Shirt,T-Shirt,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,Blender,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,Hyderabad,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,Microwave,Microwave,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,1.0,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,Kolkata,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,Air Fryer,1.0,Credit Card,Credit Card,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,Dress,2.0,Credit Card,18-02-2024,4.0,4.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [116]:
csv_1.ffill(axis=0)

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,Aarav Sharma,Delhi,Clothing,T-Shirt,55000.0,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,25000.0,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,Home & Kitchen,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,2200.0,1.0,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,Credit Card,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,Electronics,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,3800.0,1.0,Credit Card,10-02-2024,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,18000.0,2.0,Credit Card,18-02-2024,4.0,18000.0
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

# Replace

In [117]:
csv_1.replace(to_replace=1,value=20)
csv_1.replace(to_replace="Electronics",value="airplane")
csv_1.replace({"Transaction_ID":'[0-9]'},value=22)

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,NaN,NaN,Clothing,T-Shirt,NaN,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,Priya Singh,Delhi,Home & Kitchen,Blender,NaN,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,Vikram Gupta,Hyderabad,NaN,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,NaN,NaN,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1.0,NaN,05-02-2024,4.3,4500.0
8,1009.0,Rahul Das,Kolkata,NaN,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,Meera Joshi,Pune,Home & Kitchen,Air Fryer,NaN,1.0,Credit Card,NaN,4.7,5200.0
10,1011.0,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,Pooja Hegde,Mumbai,Clothing,Dress,NaN,2.0,Credit Card,18-02-2024,4.0,NaN
12,1013.0,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1015.0,Deepak Verma,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [118]:
csv_1.replace({"Customer_Name":'[A-z,a-z]'},22,regex=True)

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,22,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,NaN,NaN,Clothing,T-Shirt,NaN,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,22,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,22,Delhi,Home & Kitchen,Blender,NaN,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,22,Hyderabad,NaN,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,22,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,22,Mumbai,Home & Kitchen,Microwave,NaN,NaN,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,22,Chennai,Electronics,Smartwatch,4500.0,1.0,NaN,05-02-2024,4.3,4500.0
8,1009.0,22,Kolkata,NaN,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,22,Pune,Home & Kitchen,Air Fryer,NaN,1.0,Credit Card,NaN,4.7,5200.0
10,1011.0,22,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,22,Mumbai,Clothing,Dress,NaN,2.0,Credit Card,18-02-2024,4.0,NaN
12,1013.0,22,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1015.0,22,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [119]:
csv_1.replace(2,np.nan).ffill(limit=3) # replaces 1 with NaN and fills the NaN values forward up to 3 rows

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,22,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,22,Delhi,Clothing,T-Shirt,55000.0,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,22,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,22,Delhi,Home & Kitchen,Blender,25000.0,1.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,22,Hyderabad,Home & Kitchen,Headphones,2500.0,1.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,22,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,22,Mumbai,Home & Kitchen,Microwave,2200.0,1.0,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,22,Chennai,Electronics,Smartwatch,4500.0,1.0,Credit Card,05-02-2024,4.3,4500.0
8,1009.0,22,Kolkata,Electronics,Jacket,3800.0,1.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,22,Pune,Home & Kitchen,Air Fryer,3800.0,1.0,Credit Card,10-02-2024,4.7,5200.0
10,1011.0,22,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,22,Mumbai,Clothing,Dress,18000.0,1.0,Credit Card,18-02-2024,4.0,18000.0
12,1013.0,22,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,1013.0,22,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
14,1015.0,22,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

# Interpolate

In [120]:
csv_1

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001.0,22,Delhi,Electronics,Laptop,55000.0,1.0,UPI,15-01-2024,4.5,55000.0
1,1002.0,NaN,NaN,Clothing,T-Shirt,NaN,3.0,Credit Card,18-01-2024,4.0,3600.0
2,1003.0,22,Bengaluru,Electronics,Smartphone,25000.0,1.0,UPI,20-01-2024,4.8,25000.0
3,1004.0,22,Delhi,Home & Kitchen,Blender,NaN,2.0,Debit Card,22-01-2024,3.9,7000.0
4,1005.0,22,Hyderabad,NaN,Headphones,2500.0,2.0,Net Banking,25-01-2024,4.2,5000.0
5,1006.0,22,Bengaluru,Clothing,Jeans,2200.0,1.0,UPI,28-01-2024,4.1,2200.0
6,1007.0,22,Mumbai,Home & Kitchen,Microwave,NaN,NaN,Credit Card,02-02-2024,4.6,6500.0
7,1008.0,22,Chennai,Electronics,Smartwatch,4500.0,1.0,NaN,05-02-2024,4.3,4500.0
8,1009.0,22,Kolkata,NaN,Jacket,3800.0,2.0,Debit Card,10-02-2024,3.8,7600.0
9,1010.0,22,Pune,Home & Kitchen,Air Fryer,NaN,1.0,Credit Card,NaN,4.7,5200.0
10,1011.0,22,Delhi,Electronics,Tablet,18000.0,1.0,UPI,15-02-2024,4.4,18000.0
11,1012.0,22,Mumbai,Clothing,Dress,NaN,2.0,Credit Card,18-02-2024,4.0,NaN
12,1013.0,22,Bengaluru,Electronics,Monitor,14000.0,1.0,Net Banking,20-02-2024,4.5,14000.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1015.0,22,Pune,Clothing,Shirt,1500.0,4.0,Debit Card,25-02-2024,3.9,6000.0

In [121]:
# 1. Sirf number waale columns select karein
num_cols = csv_1.select_dtypes(include=[np.number]).columns

# 2. Ab interpolate karein (Aapka error 100% khatam ho jayega)
csv_1[num_cols] = csv_1[num_cols].interpolate() # it works only for numeric columns
csv_1[num_cols]

    Transaction_ID    Price  Quantity  Rating  Total_Amount
0           1001.0  55000.0       1.0     4.5       55000.0
1           1002.0  40000.0       3.0     4.0        3600.0
2           1003.0  25000.0       1.0     4.8       25000.0
3           1004.0  13750.0       2.0     3.9        7000.0
4           1005.0   2500.0       2.0     4.2        5000.0
5           1006.0   2200.0       1.0     4.1        2200.0
6           1007.0   3350.0       1.0     4.6        6500.0
7           1008.0   4500.0       1.0     4.3        4500.0
8           1009.0   3800.0       2.0     3.8        7600.0
9           1010.0  10900.0       1.0     4.7        5200.0
10          1011.0  18000.0       1.0     4.4       18000.0
11          1012.0  16000.0       2.0     4.0       16000.0
12          1013.0  14000.0       1.0     4.5       14000.0
13          1014.0   7750.0       2.5     4.2       10000.0
14          1015.0   1500.0       4.0     3.9        6000.0

# Merge

In [122]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,22,33,44]})
var2 =pd.DataFrame({'A':[1,2,3,5],'C':[12,21,13,41]})
pd.merge(var1,var2,on='A') # it works only if the columns are the same

   A   B   C
0  1  11  12
1  2  22  21
2  3  33  13

In [123]:
pd.merge(var1,var2,on='A',how="inner") # it works only

   A   B   C
0  1  11  12
1  2  22  21
2  3  33  13

In [124]:
pd.merge(var1,var2,on='A',how='left') # it will give all the rows from var1 and var2 and fill the missing values with NaN

   A   B     C
0  1  11  12.0
1  2  22  21.0
2  3  33  13.0
3  4  44   NaN

In [125]:
pd.merge(var1,var2,on='A',how='right') # it will fill the missing values with NaN

   A     B   C
0  1  11.0  12
1  2  22.0  21
2  3  33.0  13
3  5   NaN  41

In [127]:
pd.merge(var1,var2,on='A',how='outer', indicator=True)

   A     B     C      _merge
0  1  11.0  12.0        both
1  2  22.0  21.0        both
2  3  33.0  13.0        both
3  4  44.0   NaN   left_only
4  5   NaN  41.0  right_only

In [128]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,22,33,44]})
var2 =pd.DataFrame({'A':[1,2,3,5],'B':[12,21,13,41]})
pd.merge(var1,var2,on='A')

   A  B_x  B_y
0  1   11   12
1  2   22   21
2  3   33   13

In [134]:
pd.merge(var1,var2,left_index=True,right_index=True,suffixes=('_name','_id'))

   A_name  B_name  A_id  B_id
0       1      11     1    12
1       2      22     2    21
2       3      33     3    13
3       4      44     5    41

# Concate

In [136]:
sr1 = pd.Series([1,2,3,4,5])
sr2 = pd.Series([11,22,33,44])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
4     5
0    11
1    22
2    33
3    44
dtype: int64

In [157]:
d1 =pd.DataFrame({'A':[1,3,4,8],'B':[11,22,33,44]})
d2 =pd.DataFrame({'A':[1,2,5,9],'C':[12,13,41,89]})
pd.concat([d1,d2],axis=1)

   A   B  A   C
0  1  11  1  12
1  3  22  2  13
2  4  33  5  41
3  8  44  9  89

In [149]:
pd.concat([d1,d2],axis=0)

   A   B
0  1  11
1  3  22
2  4  33
3  8  44
0  1  12
1  2  13
2  5  41
3  9  89

In [156]:
d1 =pd.DataFrame({'A':[1,3,8,5],'B':[11,22,33,44]})
d2 =pd.DataFrame({'A':[1,5],'C':[12,89]})
pd.concat([d1,d2],axis=1)

   A   B    A     C
0  1  11  1.0  12.0
1  3  22  5.0  89.0
2  8  33  NaN   NaN
3  5  44  NaN   NaN

In [ ]:
pd.concat([d1,d2],axis=1,join='inner') # inner = intersection ,outer = union

   A   B  A   C
0  1  11  1  12
1  3  22  2  13
2  4  33  5  41
3  8  44  9  89

In [ ]:

pd.concat([d1,d2],axis=1,keys=('D1','D2')) # keys are used to name the columns

  D1     D2
   A   B  A   C
0  1  11  1  12
1  3  22  2  13
2  4  33  5  41
3  8  44  9  89

In [ ]:

pd.concat([d1,d2],axis=0,keys=('D1','D2'))  # keys are used to name the dataframes

      A     B     C
D1 0  1  11.0   NaN
   1  3  22.0   NaN
   2  4  33.0   NaN
   3  8  44.0   NaN
D2 0  1   NaN  12.0
   1  2   NaN  13.0
   2  5   NaN  41.0
   3  9   NaN  89.0

In [163]:
d1 =pd.DataFrame({'A':[1,3,8,5],}) #1D dataframe
d2 =pd.DataFrame({'A':[1,5],'C':[12,89]})#2D dataframe
pd.concat([d1,d2])

   A     C
0  1   NaN
1  3   NaN
2  8   NaN
3  5   NaN
0  1  12.0
1  5  89.0

In [164]:
d1 =pd.DataFrame({'D':[1,3,8,5],})
d2 =pd.DataFrame({'A':[1,5],'C':[12,89]})
pd.concat([d1,d2],axis=1)

   D    A     C
0  1  1.0  12.0
1  3  5.0  89.0
2  8  NaN   NaN
3  5  NaN   NaN