# Melt Function

In [7]:
import pandas as pd
import numpy as np

In [ ]:
var  = pd.DataFrame({"days":[1,2,3,4,5,6],"eng": [10,60,49,35,56,34],"math":[20,50,45,32,34,56],"science":[30,40,45,32,34,56]})
var

   days  eng  math  science
0     1   10    20       30
1     2   60    50       40
2     3   49    45       45
3     4   35    32       32
4     5   56    34       34
5     6   34    56       56

In [10]:
pd.melt(var) # vericaly reshape

   variable  value
0      days      1
1      days      2
2      days      3
3      days      4
4      days      5
5      days      6
6       eng     10
7       eng     60
8       eng     49
9       eng     35
10      eng     56
11      eng     34
12     math     20
13     math     50
14     math     45
15     math     32
16     math     34
17     math     56
18  science     30
19  science     40
20  science     45
21  science     32
22  science     34
23  science     56

In [17]:
pd.melt(var,id_vars=["days"],var_name="subject",value_name="marks")

    days  subject  marks
0      1      eng     10
1      2      eng     60
2      3      eng     49
3      4      eng     35
4      5      eng     56
5      6      eng     34
6      1     math     20
7      2     math     50
8      3     math     45
9      4     math     32
10     5     math     34
11     6     math     56
12     1  science     30
13     2  science     40
14     3  science     45
15     4  science     32
16     5  science     34
17     6  science     56

# Pivot

In [23]:
var  = pd.DataFrame({"days":[1,2,3,4,5,6],'students':["a",'b','c','d','e','f'],"eng": [10,60,49,35,56,34],"math":[20,50,45,32,34,56],"science":[30,40,45,32,34,56]})
var.pivot(index="days",columns="students")

           eng                                math                          \
students     a     b     c     d     e     f     a     b     c     d     e
days
1         10.0   NaN   NaN   NaN   NaN   NaN  20.0   NaN   NaN   NaN   NaN
2          NaN  60.0   NaN   NaN   NaN   NaN   NaN  50.0   NaN   NaN   NaN
3          NaN   NaN  49.0   NaN   NaN   NaN   NaN   NaN  45.0   NaN   NaN
4          NaN   NaN   NaN  35.0   NaN   NaN   NaN   NaN   NaN  32.0   NaN
5          NaN   NaN   NaN   NaN  56.0   NaN   NaN   NaN   NaN   NaN  34.0
6          NaN   NaN   NaN   NaN   NaN  34.0   NaN   NaN   NaN   NaN   NaN

               science
students     f       a     b     c     d     e     f
days
1          NaN    30.0   NaN   NaN   NaN   NaN   NaN
2          NaN     NaN  40.0   NaN   NaN   NaN   NaN
3          NaN     NaN   NaN  45.0   NaN   NaN   NaN
4          NaN     NaN   NaN   NaN  32.0   NaN   NaN
5          NaN     NaN   NaN   NaN   NaN  34.0   NaN
6         56.0     NaN   NaN   NaN   NaN   NaN  56.0

In [25]:
# get specific column data
var.pivot(index="days",columns="students",values="math")

students     a     b     c     d     e     f
days
1         20.0   NaN   NaN   NaN   NaN   NaN
2          NaN  50.0   NaN   NaN   NaN   NaN
3          NaN   NaN  45.0   NaN   NaN   NaN
4          NaN   NaN   NaN  32.0   NaN   NaN
5          NaN   NaN   NaN   NaN  34.0   NaN
6          NaN   NaN   NaN   NaN   NaN  56.0

# Pivot table

In [27]:
# for operations
var.pivot_table(index="days",columns="students",aggfunc="sum")

           eng                                math                          \
students     a     b     c     d     e     f     a     b     c     d     e
days
1         10.0   NaN   NaN   NaN   NaN   NaN  20.0   NaN   NaN   NaN   NaN
2          NaN  60.0   NaN   NaN   NaN   NaN   NaN  50.0   NaN   NaN   NaN
3          NaN   NaN  49.0   NaN   NaN   NaN   NaN   NaN  45.0   NaN   NaN
4          NaN   NaN   NaN  35.0   NaN   NaN   NaN   NaN   NaN  32.0   NaN
5          NaN   NaN   NaN   NaN  56.0   NaN   NaN   NaN   NaN   NaN  34.0
6          NaN   NaN   NaN   NaN   NaN  34.0   NaN   NaN   NaN   NaN   NaN

               science
students     f       a     b     c     d     e     f
days
1          NaN    30.0   NaN   NaN   NaN   NaN   NaN
2          NaN     NaN  40.0   NaN   NaN   NaN   NaN
3          NaN     NaN   NaN  45.0   NaN   NaN   NaN
4          NaN     NaN   NaN   NaN  32.0   NaN   NaN
5          NaN     NaN   NaN   NaN   NaN  34.0   NaN
6         56.0     NaN   NaN   NaN   NaN   NaN  56.0

In [33]:
var  = pd.DataFrame({"days":[1,1,1,1,2,2],'students':["a",'b','a','b','a','b'],"eng": [10,60,49,35,56,34],"math":[20,50,45,32,34,56],"science":[30,40,45,32,34,56]})
var

   days students  eng  math  science
0     1        a   10    20       30
1     1        b   60    50       40
2     1        a   49    45       45
3     1        b   35    32       32
4     2        a   56    34       34
5     2        b   34    56       56

In [35]:
var.pivot_table(index="students",columns="days",aggfunc="sum",margins=True)

          eng          math          science
days        1   2  All    1   2  All       1   2  All
students
a          59  56  115   65  34   99      75  34  109
b          95  34  129   82  56  138      72  56  128
All       154  90  244  147  90  237     147  90  237